### ISSUE TITLE
ProgrammingError: column t1.given_name does not exist

### ISSUE THREAD

**Issue by lniesz** [quay/quay-operator#209] opened 2020-05-06 08:34 UTC
I have an Openshift v4.3.9 cluster (3 x masters, 3 x workers) and trying to use Quay operator.
The install seems to be ok with the basic config plus with Clair enabled.
Checking the logs of the POD: example-quayecosystem-quay-config-xxx I can see many errors like the following:
.
.
.
2020-05-06 06:43:40,861 [61] [DEBUG] [peewee] ('SELECT "t1"."id", "t1"."uuid", "t1"."username", "t1"."password_hash", "t1"."email", "t1"."verified", "t1"."stripe_id", "t1"."organization", "t1"."robot", "t1"."invoice_email", "t1"."invalid_login_attempts", "t1"."last_invalid_login", "t1"."removed_tag_expiration_s", "t1"."enabled", "t1"."invoice_email_address", "t1"."given_name", "t1"."family_name", "t1"."company", "t1"."location", "t1"."maximum_queued_builds_count", "t1"."creation_date", "t1"."last_accessed" FROM "user" AS "t1" LIMIT %s', [1])
gunicorn-config stdout | 2020-05-06 06:43:40,861 [61] [DEBUG] [peewee] ('SELECT "t1"."id", "t1"."uuid", "t1"."username", "t1"."password_hash", "t1"."email", "t1"."verified", "t1"."stripe_id", "t1"."organization", "t1"."robot", "t1"."invoice_email", "t1"."invalid_login_attempts", "t1"."last_invalid_login", "t1"."removed_tag_expiration_s", "t1"."enabled", "t1"."invoice_email_address", "t1"."given_name", "t1"."family_name", "t1"."company", "t1"."location", "t1"."maximum_queued_builds_count", "t1"."creation_date", "t1"."last_accessed" FROM "user" AS "t1" LIMIT %s', [1])
2020-05-06 06:43:40,873 [61] [DEBUG] [data.database] Disconnecting from database.
gunicorn-config stdout | 2020-05-06 06:43:40,873 [61] [DEBUG] [data.database] Disconnecting from database.
2020-05-06 06:43:40,873 [61] [ERROR] [gunicorn.error] Error handling request /api/v1/superuser/config/createsuperuser
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/utils/cors.py", line 35, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/quay-registry/config_app/config_endpoints/api/__init__.py", line 26, in handle_error
    return super(ApiExceptionHandlingApi, self).handle_error(error)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/utils/cors.py", line 35, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/quay-registry/config_app/config_endpoints/api/__init__.py", line 26, in handle_error
    return super(ApiExceptionHandlingApi, self).handle_error(error)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/quay-registry/config_app/config_endpoints/api/__init__.py", line 140, in wrapped
    return func(self, *args, **kwargs)
  File "/quay-registry/config_app/config_endpoints/api/suconfig.py", line 178, in post
    if config_provider.config_exists() and not database_has_users():
  File "/quay-registry/config_app/config_endpoints/api/suconfig.py", line 35, in database_has_users
    return model.has_users()
  File "/quay-registry/config_app/config_endpoints/api/suconfig_models_pre_oci.py", line 17, in has_users
    return bool(list(User.select().limit(1)))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 6655, in __iter__
    self.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 1812, in inner
    return method(self, database, *args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 1883, in execute
    return self._execute(database)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 2054, in _execute
    cursor = database.execute(self)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 3018, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/quay-registry/data/database.py", line 195, in execute_sql
    cursor = super(RetryOperationalError, self).execute_sql(sql, params, commit)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 3012, in execute_sql
    self.commit()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 2783, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
ProgrammingError: column t1.given_name does not exist
LINE 1: ...s", "t1"."enabled", "t1"."invoice_email_address", "t1"."give...
                                                             ^

gunicorn-config stdout | 2020-05-06 06:43:40,873 [61] [ERROR] [gunicorn.error] Error handling request /api/v1/superuser/config/createsuperuser
.
.
.

**Comment by lniesz** [comment] 2020-08-05 10:06
It seems noone really cares this problem :-(
In the last 6 month I was not able to do consistent successful installs of quay.
Now my Openshift is on 4.5 and quay-operator is 3.3, but I still have the same problem.
Postgresql reporting this column does not exist error and quayecosystem tells:       message: >-
        Failed to create superuser: invalid character '<' looking for beginning
        of value
In the last 2 days I've tried with and without precreated superuser secret, also tried with skipSetup and giving all parameters manually on quay config page (then I was not able to specify some required fields, however those were given at the creation of Quayecosystem object).
I'm quite disappointed with this now :-(

**Comment by ricardomaraschini** [comment] 2022-01-17 10:55
@lniesz the operator went through a massive rewrite from version 3.3 to version 3.4. Are you still unable to deploy the latest versions?

**Comment by lniesz** [comment] 2022-01-17 12:58
@ricardomaraschini
Hi, I have not tried it recently

**Comment by ricardomaraschini** [comment] 2022-01-17 14:07
This seems to be a problem during the database "migration" (or initialization). I can't reproduce it in the latest release so I recommend you to upgrade to it (v3.6.2). I am closing this issue as it refers to a very old version. Feel free to reopen if you think it is still relevant.

**Closed as completed by ricardomaraschini** 2022-01-17 14:07 UTC
