### ISSUE TITLE
Install fails for OCP 4.3.5 with Failed to create superuser: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by mueroema** [quay/quay-operator#170] opened 2020-03-24 16:51 UTC
tested it several times with default and advanced settings, no success. Attached here the config log and the last used QuayEcosystem.

Operator hangs on:
{"level":"info","ts":1585068496.0442173,"logger":"controller_quayecosystem","msg":"Reconciling QuayEcosystem","Request.Namespace":"quay-enterprise","Request.Name":"quayecosystem"}
{"level":"info","ts":1585068500.850729,"logger":"controller_quayecosystem","msg":"Running exec into Pod","Reason":"","Pod Name":"quayecosystem-quay-postgresql-5f589fc56d-d4klc"}
{"level":"info","ts":1585068500.968957,"logger":"controller_quayecosystem","msg":"Running exec into Pod","Reason":"","Pod Name":"quayecosystem-quay-postgresql-5f589fc56d-d4klc"}
{"level":"error","ts":1585068511.797454,"logger":"controller_quayecosystem","msg":"Failed to create superuser","error":"invalid character '<' looking for beginning of value","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/setup.(*QuaySetupManager).SetupQuay\n\t/home/runner/work/quay-operator/quay-operator/pkg/controller/quayecosystem/setup/setup.go:128\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem.(*ReconcileQuayEcosystem).Reconcile\n\t/home/runner/work/quay-operator/quay-operator/pkg/controller/quayecosystem/quayecosystem_controller.go:231\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88"}

[debug-config.LOG](https://github.com/redhat-cop/quay-operator/files/4376559/debug-config.LOG)
[quay.zip](https://github.com/redhat-cop/quay-operator/files/4376564/quay.zip)

**Comment by kurtismullins** [comment] 2020-03-25 16:04
@mueroema Did you specify a custom superuser name? Or did this error occur using the default values?

**Comment by mueroema** [comment] 2020-03-25 16:38
Both times. I was starting with the quick install and all default settings. As this error raised first time, I was using my own superuser.

**Comment by kurtismullins** [comment] 2020-03-25 17:06
@mueroema Interesting.

Would it be possible to share your CR `.yaml` file that you're using?
Also, what version of the operator are you using? Or are you running it directly off of `master`?

**Comment by mueroema** [comment] 2020-03-25 18:13
it is attached in the quay.zip already. It is a OCP 4.3.5 cluster with 3 master, 3 workers a typical Hetzner installation. With that I have used the Operator Hub installation that will provided with the OCP Cluster console.

**Comment by KrisJohnstone** [comment] 2020-04-23 04:25
Also happening for me on OCP 4.3.0 with 1.0.2.

**Comment by KrisJohnstone** [comment] 2020-05-28 06:32
For me with 1.1.0 at least, the issue was the superuser had a capital character.

**Comment by krishchow** [comment] 2020-08-17 22:43
Bump - getting this issue on an OCP 4.5.5 cluster too

**Comment by ricardomaraschini** [comment] 2022-01-17 14:22
This seems to be a problem caused by a failure during the database initialization. In quay log I can read:

```
ProgrammingError: column t1.given_name does not exist
LINE 1: ...s", "t1"."enabled", "t1"."invoice_email_address", "t1"."give...
```

The current version of the operator is v3.6.2. Can you validate if it this problem happens in the latest release?

**Comment by ricardomaraschini** [comment] 2022-01-24 10:41
I am closing this one. If you are yet having this issue please upgrade to the latest version.

**Closed as completed by ricardomaraschini** 2022-01-24 10:41 UTC
